export const translations = {
   es: {
      menu: {
         customerService: "Servicio al cliente",
         documents: "Documentos",
         profile: "Perfil",
         gallery: "Galería",
      },
      screen: {
         users: "Usuarios",
         addUser: "Agregar usuario",
         documents: "Documentos",
         reports: "Reportes",
         status: "Estatus",
         ratings: "Valoraciones",
         history: "Historial",
      },
      login: {
         title: "DESARROLLOS URBANOS",
         email: "Correo electrónico",
         password: "Contraseña",
         button: "Iniciar",
         forgotPassword: "¿Olvidaste tu contraseña?",
         invalidEmail: "Debes proporcionar un correo válido",
         invalidPassword: "Debes proporcionar una contraseña válida",
      },
      recoverPassword: {
         title: "Recuperar contraseña",
         email: "Correo electrónico",
         send: "Enviar",
         back: "Regresar",
         invalidEmail: "Debes proporcionar un correo válido",
         error: "No se pudo enviar la información, intente nuevamente.",
         sent: "Correo enviado.",
      },
      updatePassword: {
         title: "Actualizar contraseña",
         password: "Contraseña nueva",
         repassword: "Repetir contraseña",
         send: "Enviar",
         invalidPassword: "Debes proporcionar una contraseña válida",
         invalidRePassword: "Las contraseñas no coinciden",
         error: "No se pudo actualizar la contraseña, intente nuevamente.",
      },
      profile: {
         logout: "Cerrar sesión",
         users: "Usuarios",
         error: "No se pudo obtener la información del usuario.",
      },
      users: {
         title: "Usuarios",
         add: "Agregar usuario",
         error: "No se pudieron obtener los usuarios.",
      },
      addUser: {
         title: "Agregar usuario",
         unit: "Unidad",
         name: "Nombre",
         lastName: "Apellidos",
         email: "Correo electrónico",
         phone: "Teléfono",
         add: "Agregar",
         invalidUnit: "Debes proporcionar una unidad válida.",
         invalidName: "Debes proporcionar un nombre válido.",
         invalidLastName: "Debes proporcionar un apellido válido.",
         invalidEmail: "Debes proporcionar un correo válido.",
         error: "No se pudo agregar al usuario.",
         added: "Usuario agregado correctamente.",
      },
   },
   en: {
      menu: {
         customerService: "Customer service",
         documents: "Documents",
         profile: "Profile",
         gallery: "Gallery",
      },
      screen: {
         users: "Users",
         addUser: "Add user",
         documents: "Documents",
         reports: "Reports",
         status: "Status",
         ratings: "Ratings",
         history: "History",
      },
      login: {
         title: "URBAN DEVELOPMENTS",
         email: "Email",
         password: "Password",
         button: "Start",
         forgotPassword: "Forgot your password?",
         invalidEmail: "You must provide a valid email",
         invalidPassword: "You must provide a valid password",
      },
      recoverPassword: {
         title: "Recover password",
         email: "Email",
         send: "Send",
         back: "Back",
         invalidEmail: "You must provide a valid email",
         error: "Could not send the information, try again.",
         sent: "Email sent.",
      },
      updatePassword: {
         title: "Update password",
         password: "New password",
         repassword: "Repeat password",
         send: "Send",
         invalidPassword: "You must provide a valid password",
         invalidRePassword: "Passwords do not match",
         error: "Could not update the password, try again.",
      },
      profile: {
         logout: "Log out",
         users: "Users",
         error: "Could not get user information.",
      },
      users: {
         title: "Users",
         add: "Add user",
         error: "Could not get users.",
      },
      addUser: {
         title: "Add user",
         unit: "Unit",
         name: "Name",
         lastName: "Last name",
         email: "Email",
         phone: "Phone",
         add: "Add",
         invalidUnit: "You must provide a valid unit.",
         invalidName: "You must provide a valid name.",
         invalidLastName: "You must provide a valid last name.",
         invalidEmail: "You must provide a valid email.",
         error: "Could not add the user.",
         added: "User added correctly.",
      },
   },
};
