export const translations = {
  es: {
    menu: {
      customerService: "Servicio al cliente",
      documents: "Documentos",
      profile: "Perfil",
      gallery: "Galería",
    },
    screen: {
      users: "Usuarios",
      addUser: "Agregar usuario",
      documents: "Documentos",
      reports: "Reportes",
      status: "Estatus",
      ratings: "Valoraciones",
      history: "Historial",
      notifications: "Notificaciones",
      newReport: "Nuevo reporte",
    },
    button: {
      add: "Agregar",
      back: "Regresar",
      next: "Siguiente",
      finish: "Finalizar",
      accept: "Aceptar",
      send: "Enviar",
      start: "Iniciar",
      cancel: "Cancelar",
    },
    error: {
      intern: "Error interno",
      date: "Debe seleccionar una fecha.",
    },
    login: {
      title: "DESARROLLOS URBANOS",
      email: "Correo electrónico",
      password: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      invalidEmail: "Debes proporcionar un correo válido",
      invalidPassword: "Debes proporcionar una contraseña válida",
    },
    recoverPassword: {
      title: "Recuperar contraseña",
      email: "Correo electrónico",
      invalidEmail: "Debes proporcionar un correo válido",
      error: "No se pudo enviar la información, intente nuevamente.",
      sent: "Correo enviado.",
    },
    updatePassword: {
      title: "Actualizar contraseña",
      desciption: "Ingrese su nueva contraseña.",
      password: "Contraseña nueva",
      repassword: "Confirmar contraseña",
      invalidPassword: "Debes proporcionar una contraseña válida",
      invalidRePassword: "Las contraseñas no coinciden",
      error: "No se pudo actualizar la contraseña, intente nuevamente.",
    },
    profile: {
      logout: "Cerrar sesión",
      users: "Usuarios",
      error: "No se pudo obtener la información del usuario.",
      warranty: "Validez Garantía",
    },
    users: {
      title: "Usuarios",
      add: "Agregar usuario",
      error: "No se encontraron usuarios asociados a esta cuenta",
      errorRemove: "No se pudo eliminar el usuario.",
      remove: "¿Eliminar usuario?",
      titleRemove: "Eliminar",
      deleted: "Usuario eliminado.",
    },
    addUser: {
      title: "Agregar usuario",
      unit: "Unidad",
      name: "Nombre",
      lastName: "Apellidos",
      email: "Correo electrónico",
      phone: "Teléfono",
      invalidUnit: "Debes proporcionar una unidad válida.",
      invalidName: "Debes proporcionar un nombre válido.",
      invalidLastName: "Debes proporcionar un apellido válido.",
      invalidEmail: "Debes proporcionar un correo válido.",
      error: "No se pudo agregar al usuario.",
      added: "Usuario agregado correctamente.",
    },
    reports: {
      title: "Reportes",
      details: "Reporta aquí tu detalle",
      unit: "¿En donde ocurrió el detalle?",
      selectUnit: "Selecciona una Unidad",
      area: "¿Dónde tienes el detalle?",
      selectArea: "Selecciona un Área",
      equipment: "¿Qué equipo presenta detalle?",
      selectEquipment: "Selecciona un Equipo",
      problem: "¿Cuál es tu detalle?",
      selectProblem: "Selecciona un Detalle",
      comment: "Describa su detalle",
      comments: "Escribe aquí tu detalle",
      photos: "¿Tienes fotos o video del detalle?",
      termns1:
        "Para la atención de los detalles señalados en este reporte, el departamento de customer service contara con 48 hrs. para contactar al propietario o inquilino a fin de agendar una cita conveniente a ambos lados para ejecutar dichos trabajos.",
      note: "IMPORTANTE:",
      terms2:
        "El propietario o inquilino tendrá que estar presente al momento de que se este realizando los trabajos en el departamento.",
      newReport: "¿Quieres agregar otro reporte?",
      errorCancel: "No se pudo cancelar el reporte.",
    },
    ratings: {
      title: "Valoraciones",
      text: "Su opinion nos interesa. Ayúdenos a valorar nuestro servicio",
      thanks: "Muchas Gracias",
      errorSave: "No se pudo enviar la valoración.",
      errorSelect: "Por favor seleccione una respuesta válida.",
      thanks2: "Gracias por su valoración.",
    },
    history: {
      title: "Historial",
      unit: "Unidad",
      area: "Área",
      equipment: "Equipo",
      problem: "Problema",
      comments: "Comentarios",
    },
    documents: {
      error: "No se obtuvo informacion de carpeta",
      error2: "No se pudieron obtener las carpetas",
      error3: "No se pudieron obtener los archivos",
      loading: "Obteniendo archivo...",
    },
    notifications: {
      error: "No se pudieron obtener notificaciones",
    },
    status: {
      title: "Seleccione la fecha para la reparación",
    },
    select: {
      date: "Seleccionar fecha",
      selectDate: "Seleccione fecha",
      search: "Buscar fecha",
      empty: "No se encontraron fechas disponibles",
      unit: "Seleccionar unidad",
      selectUnit: "Seleccione una unidad",
      searchUnit: "Buscar unidad",
      emptyUnit: "No se encontraron unidades disponibles",
    },
    permissions: {
      title:
        "Para tomar fotos o video, permite que Eleva pueda usar la cámara.",
      textIOS:
        "Para tomar fotos o video, permite que Eleva pueda usar la cámara, tienes que ir a ajustes y activarlos manualmente el permiso.",
      text: "Para tomar fotos o video, permite que Eleva pueda usar la cámara.",
    },
    apiResponse: {
      login: "Usuario o contraseña invalida",
      newButton: "Vigencia no permite realizar nuevos reportes.",
      updatePassword: "No fue posible activar el usuario.",
      recoverPassword: "Correo enviado correctamente.",
      recoverPassword2: "Correo incorrecto.",
      addUser: "Datos registrado previamente.",
    },
    recoverPassword: {
      title: "Recuperar contraseña",
      description:
        "Ingrese su correo electrónico registrado para recibir un código de verificación.",
      email: "Correo electrónico",
      button: "Solicitar código",
    },
    verifyCode: {
      title: "Verificar código",
      description: "Ingrese el código de verificación enviado a su correo.",
      button: "Verificar",
    },
  },
  en: {
    menu: {
      customerService: "Customer service",
      documents: "Documents",
      profile: "Profile",
      gallery: "Gallery",
    },
    screen: {
      users: "Users",
      addUser: "Add user",
      documents: "Documents",
      reports: "Reports",
      status: "Status",
      ratings: "Ratings",
      history: "History",
      notifications: "Notifications",
      newReport: "New report",
    },
    button: {
      add: "Add",
      back: "Back",
      next: "Next",
      finish: "Finish",
      accept: "Accept",
      send: "Send",
      start: "Start",
      cancel: "Cancel",
    },
    error: {
      intern: "Internal error",
      date: "You must select a date.",
    },
    login: {
      title: "URBAN DEVELOPMENTS",
      email: "Email",
      password: "Password",
      button: "Start",
      forgotPassword: "Forgot your password?",
      invalidEmail: "You must provide a valid email",
      invalidPassword: "You must provide a valid password",
    },
    recoverPassword: {
      title: "Recover password",
      email: "Email",

      invalidEmail: "You must provide a valid email",
      error: "Could not send the information, try again.",
      sent: "Email sent.",
    },
    updatePassword: {
      title: "Update password",
      desciption: "Please enter your new password",
      password: "New password",
      repassword: "Confirm password",
      invalidPassword: "You must provide a valid password",
      invalidRePassword: "Passwords do not match",
      error: "Could not update the password, try again.",
    },
    profile: {
      logout: "Log out",
      users: "Users",
      error: "Could not get user information.",
      warranty: "Warranty Validity",
    },
    users: {
      title: "Users",
      add: "Add user",
      error: "No users associated with this account were found",
      errorRemove: "Could not remove the user.",
      remove: "Remove user?",
      titleRemove: "Remove",
      deleted: "User deleted.",
    },
    addUser: {
      title: "Add user",
      unit: "Unit",
      name: "Name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone",
      invalidUnit: "You must provide a valid unit.",
      invalidName: "You must provide a valid name.",
      invalidLastName: "You must provide a valid last name.",
      invalidEmail: "You must provide a valid email.",
      error: "Could not add the user.",
      added: "User added correctly.",
    },
    reports: {
      title: "Reports",
      details: "Report your detail here",
      unit: "Where did the detail occur?",
      selectUnit: "Select a Unit",
      area: "Where do you have the detail?",
      selectArea: "Select an Area",
      equipment: "What equipment has detail?",
      selectEquipment: "Select an Equipment",
      problem: "What is your detail?",
      selectProblem: "Select a Detail",
      comment: "Describe your detail",
      comments: "Write your detail here",
      photos: "Do you have photos or video of the detail?",
      termns1:
        "To attend the details marked on this form, the customer service department will have 48 hrs to contact the owner or the tenant in order to schedule a convenient appointment and do the necessary repairs.",
      note: "IMPORTANT:",
      terms2:
        "The owner or tenant must be present at the time the work is being done.",
      newReport: "Do you want to add another report?",
      errorCancel: "Could not cancel the report.",
    },
    ratings: {
      title: "Ratings",
      text: "Your opinion matters to us. Help us rate our service",
      thanks: "Thank you very much",
      errorSave: "Could not send the rating.",
      errorSelect: "Please select a valid answer.",
      thanks2: "Thank you for your rating.",
    },
    history: {
      title: "History",
      unit: "Unit",
      area: "Area",
      equipment: "Equipment",
      problem: "Problem",
      comments: "Comments",
    },
    documents: {
      error: "Could not get folder information",
      error2: "Could not get folders",
      error3: "Could not get files",
      loading: "Getting file...",
    },
    notifications: {
      error: "Could not get notifications",
    },
    status: {
      title: "Select the date for the repair",
    },
    select: {
      date: "Select date",
      selectDate: "Select date",
      search: "Search date",
      empty: "No dates available",
      unit: "Select unit",
      selectUnit: "Select a unit",
      searchUnit: "Search unit",
      emptyUnit: "No units available",
    },
    permissions: {
      title: "Permissions",
      textIOS:
        "To take photos or video, allow Eleva to use the camera, you have to go to settings and manually activate the permission.",
      text: "To take photos or video, allow Eleva to use the camera.",
    },
    apiResponse: {
      login: "Invalid user or password",
      newButton: "Validity does not allow new reports.",
      updatePassword: "Could not activate the user.",
      recoverPassword: "Email sent correctly.",
      recoverPassword2: "Incorrect email.",
      addUser: "Data previously registered.",
    },
    recoverPassword: {
      title: "Recover password",
      description:
        "Enter your registered email to receive a verification code.",
      email: "Email",
      button: "Request code",
    },
    verifyCode: {
      title: "Verify code",
      description: "Enter the verification code sent to your email.",
      button: "Verify",
    },
  },
};
