export const translations = {
   es: {
      menu: {
         customerService: "Servicio al cliente",
         documents: "Documentos",
         profile: "Perfil",
         gallery: "Galería",
      },
      screen: {
         users: "Usuarios",
         addUser: "Agregar usuario",
         documents: "Documentos",
         reports: "Reportes",
         status: "Estatus",
         ratings: "Valoraciones",
         history: "Historial",
         notifications: "Notificaciones",
         newReport: "Nuevo reporte",
      },
      button: {
         add: "Agregar",
         back: "Regresar",
         next: "Siguiente",
         finish: "Finalizar",
         accept: "Aceptar",
         send: "Enviar",
         start: "Iniciar",
      },
      login: {
         title: "DESARROLLOS URBANOS",
         email: "Correo electrónico",
         password: "Contraseña",
         forgotPassword: "¿Olvidaste tu contraseña?",
         invalidEmail: "Debes proporcionar un correo válido",
         invalidPassword: "Debes proporcionar una contraseña válida",
      },
      recoverPassword: {
         title: "Recuperar contraseña",
         email: "Correo electrónico",
         invalidEmail: "Debes proporcionar un correo válido",
         error: "No se pudo enviar la información, intente nuevamente.",
         sent: "Correo enviado.",
      },
      updatePassword: {
         title: "Actualizar contraseña",
         password: "Contraseña nueva",
         repassword: "Repetir contraseña",
         invalidPassword: "Debes proporcionar una contraseña válida",
         invalidRePassword: "Las contraseñas no coinciden",
         error: "No se pudo actualizar la contraseña, intente nuevamente.",
      },
      profile: {
         logout: "Cerrar sesión",
         users: "Usuarios",
         error: "No se pudo obtener la información del usuario.",
      },
      users: {
         title: "Usuarios",
         add: "Agregar usuario",
         error: "No se pudieron obtener los usuarios.",
      },
      addUser: {
         title: "Agregar usuario",
         unit: "Unidad",
         name: "Nombre",
         lastName: "Apellidos",
         email: "Correo electrónico",
         phone: "Teléfono",
         invalidUnit: "Debes proporcionar una unidad válida.",
         invalidName: "Debes proporcionar un nombre válido.",
         invalidLastName: "Debes proporcionar un apellido válido.",
         invalidEmail: "Debes proporcionar un correo válido.",
         error: "No se pudo agregar al usuario.",
         added: "Usuario agregado correctamente.",
      },
      reports: {
         title: "Reportes",
         details: "Reporta aquí tu detalle",
         unit: "¿En donde ocurrió el detalle?",
         area: "¿Dónde tienes el detalle?",
         equipment: "¿Qué equipo presenta detalle?",
         problem: "¿Cuál es tu detalle?",
         comment: "Describa su detalle",
         comments: "Escribe aquí tu detalle",
         photos: "¿Tienes fotos o video del detalle?",
         termns1:
            "Para la atención de los detalles señalados en este reporte, el departamento de customer service contara con 48 hrs. para contactar al propietario o inquilino a fin de agendar una cita conveniente a ambos lados para ejecutar dichos trabajos.",
         note: "IMPORTANTE:",
         terms2:
            "El propietario o inquilino tendrá que estar presente al momento de que se este realizando los trabajos en el departamento.",
         newReport: "¿Quieres agregar otro reporte?",
      },
   },
   en: {
      menu: {
         customerService: "Customer service",
         documents: "Documents",
         profile: "Profile",
         gallery: "Gallery",
      },
      screen: {
         users: "Users",
         addUser: "Add user",
         documents: "Documents",
         reports: "Reports",
         status: "Status",
         ratings: "Ratings",
         history: "History",
         notifications: "Notifications",
         newReport: "New report",
      },
      button: {
         add: "Add",
         back: "Back",
         next: "Next",
         finish: "Finish",
         accept: "Accept",
         send: "Send",
         start: "Start",
      },
      login: {
         title: "URBAN DEVELOPMENTS",
         email: "Email",
         password: "Password",
         button: "Start",
         forgotPassword: "Forgot your password?",
         invalidEmail: "You must provide a valid email",
         invalidPassword: "You must provide a valid password",
      },
      recoverPassword: {
         title: "Recover password",
         email: "Email",

         invalidEmail: "You must provide a valid email",
         error: "Could not send the information, try again.",
         sent: "Email sent.",
      },
      updatePassword: {
         title: "Update password",
         password: "New password",
         repassword: "Repeat password",
         invalidPassword: "You must provide a valid password",
         invalidRePassword: "Passwords do not match",
         error: "Could not update the password, try again.",
      },
      profile: {
         logout: "Log out",
         users: "Users",
         error: "Could not get user information.",
      },
      users: {
         title: "Users",
         add: "Add user",
         error: "Could not get users.",
      },
      addUser: {
         title: "Add user",
         unit: "Unit",
         name: "Name",
         lastName: "Last name",
         email: "Email",
         phone: "Phone",
         invalidUnit: "You must provide a valid unit.",
         invalidName: "You must provide a valid name.",
         invalidLastName: "You must provide a valid last name.",
         invalidEmail: "You must provide a valid email.",
         error: "Could not add the user.",
         added: "User added correctly.",
      },
      reports: {
         title: "Reports",
         details: "Report your detail here",
         unit: "Where did the detail occur?",
         area: "Where do you have the detail?",
         equipment: "What equipment has detail?",
         problem: "What is your detail?",
         comment: "Describe your detail",
         comments: "Write your detail here",
         photos: "Do you have photos or video of the detail?",
         termns1:
            "To attend the details marked on this form, the customer service department will have 48 hrs to contact the owner or the tenant in order to schedule a convenient appointment and do the necessary repairs.",
         note: "IMPORTANT:",
         terms2:
            "The owner or tenant must be present at the time the work is being done.",
         newReport: "Do you want to add another report?",
      },
   },
};
